name: Urdu Multimodal Prediction

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # allow manual trigger

jobs:
  ping-multimodal-api:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository (to access any local assets)
      - uses: actions/checkout@v3

      # Step 2: Call multimodal API with text + image
      - name: Send text and image to API
        run: |
          curl -X POST "https://oldahmed-multimodal-urdu.hf.space/predict" \
          -H "Content-Type: multipart/form-data" \
          -F "text=This is a test message" \
          -F "file=@assets/dummy.jpg"
